### ISSUE TITLE
DayOfYear and WeekOfYear produce incorrect results

### ISSUE THREAD

**Issue by justinmimbs** [RyanNHG/elm-date-format#1]
Hi Ryan,

Interesting idea to use a union type for tokens instead of a string template!

It looks like your [`dayOfYear` calculation](https://github.com/RyanNHG/elm-date-format/blob/1.0.0/src/DateFormat.elm#L549) is accidentally including, instead of excluding, the current month. This is throwing off `DayOfYear` and `WeekOfYear` results.

Is `WeekOfYear` supposed to be the [ISO week number](https://en.wikipedia.org/wiki/ISO_week_date)? If so, then your calculation will need to change, and it would likely be helpful to include a token for the week-numbering year as well (because the week-numbering year doesn't align with the calendar year).

Also, add some tests! This will give you and other users of your library more confidence. Check out [elm-test](http://package.elm-lang.org/packages/elm-community/elm-test/latest) if you haven't yet; it's really nice.

Hope this helps,

Justin

**Comment by ryan-haskell** [comment]
Thanks @justinmimbs , I'll update the code and be sure to add elm-test to verify these things are working!

**Comment by rtfeldman** [comment]
@RyanNHG This library looks **awesome** 😻

Random suggestion for future releases: if you expose individual values instead of all the union type constructors (e.g. `monthNumber : Int -> Token`, `hourNumber : Int -> Token`) then the docs will be easier to read & search, and you can introduce new constructors without breaking changes! (Adding new union type constructors when they're all exposed can break peoples' builds, due to pattern matches becoming non-exhaustive, so it requires a major version bump every time you add one. Not an issue if you decline to expose them though!)

Anyway, great stuff! We're gonna look into using this at work. ❤️

**Comment by ryan-haskell** [comment]
@rtfeldman that's perfect!

I knew exposing the union type was a wonderful way to lock in the `Token` type forever, or break people's `case token of` statements.

Exposing functions instead of the options is a great way to solve that problem!

I'll try that alternative out for sure.

**Comment by ryan-haskell** [comment]
Just added tests for all the things! `elm-test` is awesome!
